import { motion } from "framer-motion";
import { Anchor, Download } from "lucide-react";

interface SessionData {
  totalFocusedSeconds: number;
  driftCount: number;
  longestStreakMinutes: number;
  topDriftTrigger: string;
  topDriftTriggerCount?: number;
  avgReturnTimeMinutes?: number;
  totalSessionSeconds?: number;
  timeline: { minute: number; focused: boolean; type?: "focus" | "drift" | "break" }[];
}

interface NoteEntry {
  id: number;
  timestamp: string;
  text: string;
}

interface Props {
  data: SessionData;
  notes?: NoteEntry[];
  task?: string;
  onNewSession: () => void;
  onDone: () => void;
}

const SessionSummary = ({ data, notes = [], task = "", onNewSession, onDone }: Props) => {
  const formatDuration = (s: number) => {
    const h = Math.floor(s / 3600);
    const m = Math.floor((s % 3600) / 60);
    if (h > 0) return `${h}h ${m}m`;
    return `${m}m`;
  };

  const totalSession = data.totalSessionSeconds || data.totalFocusedSeconds;
  const focusPercent = totalSession > 0 ? data.totalFocusedSeconds / totalSession : 1;
  const showCongrats = focusPercent > 0.7;
  const sessionMinutes = Math.floor(totalSession / 60);

  const downloadNotesPDF = () => {
    const date = new Date().toLocaleDateString("en-US", {
      weekday: "long", year: "numeric", month: "long", day: "numeric",
    });
    const time = new Date().toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" });

    // Build PDF content using browser print
    const html = `
      <!DOCTYPE html>
      <html>
      <head>
        <meta charset="UTF-8">
        <title>ADHD Anchor - Session Notes</title>
        <style>
          * { margin: 0; padding: 0; box-sizing: border-box; }
          body { font-family: 'Helvetica Neue', Arial, sans-serif; color: #1a1a1a; padding: 48px; max-width: 700px; margin: 0 auto; }
          .header { text-align: center; margin-bottom: 36px; padding-bottom: 24px; border-bottom: 2px solid #e8e5e0; }
          .header h1 { font-size: 22px; font-weight: 600; margin-bottom: 4px; }
          .header .meta { font-size: 13px; color: #666; }
          .session-info { background: #f8f7f5; border-radius: 12px; padding: 20px; margin-bottom: 32px; }
          .session-info p { font-size: 13px; color: #444; line-height: 1.8; }
          .session-info strong { color: #1a1a1a; }
          .notes-title { font-size: 16px; font-weight: 600; margin-bottom: 16px; color: #4a7c59; }
          .note { padding: 14px 16px; margin-bottom: 10px; background: #fffdf7; border: 1px solid #f0ead6; border-radius: 10px; }
          .note .text { font-size: 14px; line-height: 1.5; }
          .note .time { font-size: 11px; color: #888; margin-top: 6px; }
          .empty { text-align: center; color: #999; font-size: 14px; padding: 40px 0; }
          .footer { text-align: center; margin-top: 40px; padding-top: 20px; border-top: 1px solid #e8e5e0; font-size: 11px; color: #aaa; }
          @media print { body { padding: 24px; } }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>ADHD Anchor - Session Notes</h1>
          <p class="meta">${date} at ${time}</p>
        </div>
        <div class="session-info">
          ${task ? `<p><strong>Task:</strong> ${task}</p>` : ""}
          <p><strong>Focused:</strong> ${formatDuration(data.totalFocusedSeconds)} &nbsp;|&nbsp; <strong>Drifts:</strong> ${data.driftCount} &nbsp;|&nbsp; <strong>Longest streak:</strong> ${data.longestStreakMinutes} min</p>
        </div>
        <p class="notes-title">Notes (${notes.length})</p>
        ${notes.length > 0
          ? notes.map((n) => `<div class="note"><p class="text">${n.text}</p><p class="time">${n.timestamp}</p></div>`).join("")
          : `<p class="empty">No notes were captured this session</p>`
        }
        <div class="footer">Generated by ADHD Anchor</div>
      </body>
      </html>
    `;

    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const printWindow = window.open(url, "_blank");
    if (printWindow) {
      printWindow.onload = () => {
        printWindow.print();
        URL.revokeObjectURL(url);
      };
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -20 }}
      transition={{ duration: 0.3 }}
      className="relative z-10 flex min-h-screen items-center justify-center px-6"
    >
      <div className="w-full max-w-md space-y-8 text-center">
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
        >
          <p className="text-muted-foreground mb-2 text-sm tracking-wide uppercase flex items-center justify-center gap-1.5">
            <Anchor size={14} />
            Anchor
          </p>
          <h1 className="text-3xl font-semibold tracking-tight text-foreground md:text-4xl">
            Session Complete
          </h1>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.35 }}
          className="space-y-4"
        >
          {showCongrats && (
            <p className="text-sage font-medium text-sm">That's a solid session ✨</p>
          )}
          <div className="space-y-1">
            <p className="text-4xl font-bold text-foreground">{formatDuration(data.totalFocusedSeconds)}</p>
            <p className="text-sm text-muted-foreground">focused</p>
          </div>

          <div className="space-y-3 text-left rounded-2xl bg-card border border-border p-5">
            <div className="flex items-center gap-3">
              <div className="h-2.5 w-2.5 rounded-full bg-terracotta" />
              <span className="text-foreground">{data.driftCount} drifts caught</span>
            </div>
            <div className="flex items-center gap-3">
              <div className="h-2.5 w-2.5 rounded-full bg-sage" />
              <span className="text-foreground">Longest streak: {data.longestStreakMinutes} minutes</span>
            </div>
            {data.topDriftTrigger && (
              <div className="flex items-center gap-3">
                <div className="h-2.5 w-2.5 rounded-full bg-terracotta" />
                <span className="text-foreground">
                  Top drift trigger: {data.topDriftTrigger}
                  {data.topDriftTriggerCount && data.driftCount > 0
                    ? ` (${data.topDriftTriggerCount} of ${data.driftCount} drifts)`
                    : ""}
                </span>
              </div>
            )}
            <div className="flex items-center gap-3">
              <div className="h-2.5 w-2.5 rounded-full bg-sage" />
              <span className="text-foreground">Avg return time: {data.avgReturnTimeMinutes || 2} min</span>
            </div>
          </div>
        </motion.div>

        {/* Segmented timeline bar */}
        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.5 }}
          className="rounded-2xl bg-card border border-border p-5"
        >
          <p className="text-xs text-muted-foreground mb-3">Focus timeline</p>
          <div className="flex h-5 w-full rounded-full overflow-hidden gap-[1px]">
            {data.timeline.map((point, i) => {
              const segType = point.type || (point.focused ? "focus" : "drift");
              const colorClass = segType === "focus"
                ? "bg-sage"
                : segType === "drift"
                ? "bg-terracotta"
                : "bg-muted";
              return (
                <div
                  key={i}
                  className={`flex-1 ${colorClass} ${i === 0 ? "rounded-l-full" : ""} ${i === data.timeline.length - 1 ? "rounded-r-full" : ""}`}
                />
              );
            })}
          </div>
          <div className="flex justify-between mt-2">
            <span className="text-xs text-muted-foreground">0 min</span>
            <span className="text-xs text-muted-foreground">{sessionMinutes} min</span>
          </div>
        </motion.div>

        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.6 }}
          className="rounded-2xl bg-card border border-border p-5 border-l-[3px] border-l-sage text-left"
        >
          <p className="text-sm text-foreground leading-relaxed">
            You tend to drift around the 25-minute mark. A short break at 20 minutes might help next time.
          </p>
        </motion.div>

        {/* Download notes as PDF */}
        {notes.length > 0 && (
          <motion.div
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.7 }}
          >
            <button
              onClick={downloadNotesPDF}
              className="w-full flex items-center justify-center gap-2 rounded-2xl border border-border py-3 text-sm font-medium text-foreground transition-all hover:bg-secondary active:scale-[0.98]"
            >
              <Download size={16} />
              Download notes ({notes.length})
            </button>
          </motion.div>
        )}

        <motion.div
          initial={{ opacity: 0, y: 10 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.8 }}
          className="flex gap-3"
        >
          <button
            onClick={onNewSession}
            className="btn-primary-action flex-1 rounded-2xl py-3.5 font-semibold"
          >
            Start new session
          </button>
          <button
            onClick={onDone}
            className="flex-1 rounded-2xl border border-border py-3.5 font-medium text-foreground transition-all hover:bg-secondary active:scale-[0.98]"
          >
            Done for today
          </button>
        </motion.div>
      </div>
    </motion.div>
  );
};

export default SessionSummary;
